### ISSUE TITLE
Random test reports (since Dancer2 0.159003?)

### ISSUE THREAD

**Issue by eserte** [drebolo/Dancer2-Plugin-RoutePodCoverage#1]
http://matrix.cpantesters.org/?dist=Dancer2-Plugin-RoutePodCoverage%200.071 shows a random pattern of pass and fail reports.

http://analysis.cpantesters.org/reports_by_field?distv=Dancer2-Plugin-RoutePodCoverage-0.071;field=mod%3ADancer2 shows that fail reports started to appear with Dancer2 0.159003 and later (which might be coincidence, or the reason for the problem).

**Comment by drebolo** [comment]
This should be fixed now.
